### ISSUE TITLE
How I can use it in 5.2 php version.

### ISSUE THREAD

**Issue by BaluRaut** [alfallouji/DHL-API#11]

**Comment by alfallouji** [comment]
Hi Baluraut,

You have to modify the code, remove namespaces, rename classes and adapt many part of the code.

If upgrading your PHP version is a possible option in your context, you should really consider it. PHP 5.2 is pretty old and you will get lot of benefits (speed, bug fixes, new features) by upgrading to the latest version of PHP.

Cheers,
