### ISSUE TITLE
Fatal error: Call to undefined method SimpleXMLElement::toXML() in DHL/Datatype/Base.php on line 118

### ISSUE THREAD

**Issue by josephm153** [alfallouji/DHL-API#14]
When trying to use the GetQuote sample, I get the following error:
Fatal error: Call to undefined method SimpleXMLElement::toXML() in DHL/Datatype/Base.php on line 118

It appears that echo $sample->toXML(); on line 76 is calling the above method in Base.php that causes the fatal error.

Any ideas?  I'm using PHP 5.3.29 on Linux (Apache webserver 2.4.12)

Thanks,

Joseph

**Comment by josephm153** [comment]
A clarification - it seems to run fine standalone, but calling it from within WordPress it gives the error I mentioned.

**Comment by alfallouji** [comment]
Hi Joseph,

Could you please provide a print_r() of $sample (before calling the toXML()).

Thanks,
