### ISSUE TITLE
where to find the configuration parameters for use DHL-API?

### ISSUE THREAD

**Issue by Metalmacana** [alfallouji/DHL-API#18]
where to find the configuration parameters for use DHL-API?
YOUR_ID, YOUR_PASS, shipperAccountNumber, billingAccountNumber, dutyAccountNumber
Thanks for the help I can provide

**Comment by alfallouji** [comment]
You need to register an account with DHL. 

You can do that by going to that URL : http://www.dhl.com.au/en/express/resource_center/integrated_shipping_solutions/integrating_xml_services.html
