### ISSUE TITLE
ShipmentValidationRequest XML issue

### ISSUE THREAD

**Issue by jason-FLS** [alfallouji/DHL-API#9]
Hi Al-fallouji,
Thank you for providing this, its been extremely helpful!

I ran into an issue while using the ShipmentValidateRequest object. Whenever I try to convert this object into XML, I get an XML piece element placed in another XML piece element.The XML in question. I am using the ShipmentValidateRequest located in Entity/AM folder.
```
     <Pieces>
         <Piece>
            <Piece>
               <PieceID>1</PieceID>
               <PackageType>CP</PackageType>
               <Weight>2</Weight>
               <Width>1</Width>
               <Height>1</Height>
               <Depth>1</Depth>
               <PieceContents>box</PieceContents>
            </Piece>
         </Piece>
      </Pieces>
```
the code in question I'm using to add pieces to the object:
```
foreach ($this->packages as $package) {
 $piece = new Piece();
 $piece->PieceID = $package->id;
 $piece->PackageType = 'CP'; 
 $piece->Weight = ceil($package->weight);
 $piece->Width = ceil($package->width);
 $piece->Height = ceil($package->height);
 $piece->Depth = ceil($package->length);

 $shipmentConfirmationRequest->ShipmentDetails->addPiece($piece);
}
```
I don't know if its an issue with the toXML function that your client is using, or if its another issue. Any help would be appreciated.

Thank you for your time,

Jason

**Comment by suriyabaskaran** [comment]
@jason-FLS , How did you solve this issue?

**Comment by jason-FLS** [comment]
@suriyabaskaran In the ShipmentDetails.php, just change the Pieces parameter type to accept a Piece object instead of a Pieces object. Its not a great fix but it seemed to do the trick for me.
```
'Pieces' => array(
            'type' => 'Piece',
            'required' => false,
            'subobject' => true,
            'multivalues' => true,
        ),
```

**Comment by alfallouji** [comment]
@jason-FLS  : this is actually the right way to do it :)

I just updated the master branch.
